# Generated by Django 4.1.6 on 2023-02-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taskmodel",
            name="deadline",
        ),
        migrations.RemoveField(
            model_name="taskmodel",
            name="status",
        ),
        migrations.AddField(
            model_name="taskmodel",
            name="is_done",
            field=models.BooleanField(default=False),
        ),
    ]
