# Generated by Django 4.1.6 on 2023-02-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_remove_taskmodel_deadline_remove_taskmodel_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskmodel",
            name="priority",
            field=models.CharField(
                choices=[
                    ("high", "Высокий"),
                    ("medium", "Средний"),
                    ("low", 'Низкий')
                ],
                default="medium",
                max_length=6,
                verbose_name="Приоритет"
            ),
        ),
    ]
